// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReStock.DataProvider;

namespace ReStock.DataProvider.Migrations
{
    [DbContext(typeof(RestockDbContext))]
    partial class RestockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReStock.Models.StockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StockItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = "2",
                            Name = "Thing",
                            StockType = "FruitsAndVeggies"
                        },
                        new
                        {
                            Id = 2,
                            Amount = "1",
                            Name = "Thing 2",
                            StockType = "Proteins"
                        },
                        new
                        {
                            Id = 3,
                            Amount = "4",
                            Name = "Thing 3",
                            StockType = "Spices"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
